apiVersion: v1
kind: Pod
metadata:
  name: mongodb-azure3
spec:
  volumes:
  - name: mongodb-data
    azureDisk:
      diskName: myAKSDisk3
      diskURI: /subscriptions/a546f3d0-30b7-42b6-affb-1ef22734bfac/resourceGroups/MC_padclusterrg_padclustername_eastus/providers/Microsoft.Compute/disks/myAKSDisk3
      kind: Managed
      fsType: ext4
  containers:
  - image: mongo
    name: mongodb
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
    ports:
    - containerPort: 27017
      protocol: TCP