kind: Deployment
apiVersion: apps/v1
metadata:
  name: react-client-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-client-app
  template:
    metadata:
      labels:
        app: react-client-app
    spec:
      containers:
        - name: react-client-app
          image: docker.io/rushaniia/react-client-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
kind: Service
apiVersion: v1
metadata:
  name: react-client-app
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: react-client-app