name: .NET

on:
  push:
    branches: [ master, release/*, feature/*]
  pull_request:
    branches: [ master, release/*, feature/* ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ../../PneumoniaAutoDiagnosis
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
